import React, { useState } from "react";
import { her, abt } from "../assets";
import { Link } from "react-router-dom";
import { Loader, Cardshw, FormField } from "../components";

let RenderCards = ({ data, title }) => {
  if (data?.lenght > 0) {
    return data.map((post) => <Cardshw key={post._id} {...post} />);
  }
  return <h2 className="mt-5 font-bold text-black text-xl "> {title}</h2>;
};

let Home = () => {
  let [loading, setloading] = useState(false);
  let [allposts, setposts] = useState(null);
  let [searchText, setsearchText] = useState("");
  return (
    <section>
      <div className="w-full h-[9rem] sm:h-[20rem] bg-gradient-to-r from-[#dd3675] via-[#e50611] to-[#dd3675] mt-4 sm:mt-12 rounded-xl flex justify-between items-center text-white hover:shadow-2xl ">
        <div className=" sm:ml-8 ">
          <img
            src={her}
            alt="heroic image"
            className="obeject-contain w-[30rem] h-[9rem] sm:w-[30rem] sm:h-[20rem] "
          />
        </div>
        <div className=" text-[0.76rem] w-30  sm:w-[17.2rem] mt-2 sm:mr-8 ">
          <h2 className="font-bold text-[0.8rem] sm:text-3xl ">
            You Imagination came alive
          </h2>
          <p className="mt-2 sm:text-sm ">
            {" "}
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam,
            impedit ipsam distinctio molestiae quod dolores sunt repudiandae
          </p>
          <div className="pt-4">
            <Link
              to="/createPost"
              className="w-28  text-center text-white hover:underline "
            >
              Craft your thoughts now &rarr;
            </Link>
          </div>
        </div>
      </div>

      <div className="sm:flex sm:justify-between sm:items-center bg-[#fff5f5] rounded-2xl shadow-lg hover:shadow-2xl mt-12 mb-12 ">
        <div className="sm:w-[60%] ">
          <h2 className="font-bold text-[1.3rem] sm:text-3xl pl-4 pt-3 ">
            About US
          </h2>
          <p className="pt-4 pb-4 pl-4 w-[95%]">
            In the heart of our digital atelier, whispers of creativity dance
            through the circuits, giving life to pixels in ways unimaginable.
            This is the tale of our Image Generative AI, a poetic symphony
            conducted by the enigmatic Generative Adversarial Networks.In the
            spotlight is our artistic maestro, the Generator. It weaves dreams
            from the randomness of whispers, creating visual poetry that
            captures the essence of imagination.Amidst the canvas, challenges
            emerge like shadows in the moonlight. Mode collapse, a delicate
            dance between stability and innovation, all painted with the
            elegance of hyperparameter brushes.This is more than technology;
            it's a vision for a world where pixels are the poets, where every
            image whispers stories and every creation is a canvas for the soul.
          </p>
        </div>
        <div className="sm:w-[40%] hidden sm:block ">
          <img src={abt} className="sm:h-[21rem] sm:w-[40rem] " />
        </div>
      </div>
      <section>
        <div>
          <h1 className="font-bold text-[#222328] text-2xl">
            The Community Showcase
          </h1>
          <p className="mt-2 text-[#666e75] text-sm max-w-full ">
            {" "}
            Browse through a collection of imaginative and visually stunning
            website generated by DALL-E AI
          </p>
        </div>
        <div className="mt-16">
          <FormField />
        </div>
        <div className="mt-10">
          {loading ? (
            <div className="flex justify-center items-center">
              {" "}
              <Loader />{" "}
            </div>
          ) : (
            <>
              {searchText && (
                <h2 className=" font-medium text-[#666e75] text-xl ">
                  {" "}
                  Showing results for{" "}
                  <span className="text-[#222328]"> {searchText} </span>
                </h2>
              )}
              <div className=" grid lg:grid-col-4 sm:grid-col-3 xs:grid-col-2 grid-col-1 gap-3 ">
                {searchText ? (
                  <RenderCards data={[]} title="No search result found" />
                ) : (
                  <RenderCards data={[]} title="No posts found" />
                )}
              </div>
            </>
          )}
        </div>
      </section>
      {/* <div className="w-full h-[34vh] mt-12 sm:mt-14 sm:flex sm:justify-between ">
        <div className=" h-[30vh] sm:w-[43%]  bg-slate-100  rounded-xl hover:shadow-xl ">
          <h1 className="object-contain font-bold text-xl ml-6 pt-6 sm:text-2xl">
            About Us
          </h1>
          <p className="w-[90%] ml-6 mr-4 ">
            Lorem, ipsum dolor sit amet consectetur adipisicing elit. Earum aut
            molestiae doloribus labore possimus dolorem ipsam aliquid tempora
            eligendi velit. Sed voluptate voluptatibus quis tenetur aspernatur
            optio ullam blanditiis adipisci.
          </p>
        </div>
        <div className=" h-[30vh] sm:w-[43%] mt-6 sm:mt-0 bg-slate-100 rounded-xl hover:shadow-xl ">
          <h1 className="object-contain font-bold text-xl ml-6 pt-6 sm:text-2xl">
            About Us
          </h1>
          <p className="w-[90%] ml-6 mr-4 ">
            Lorem, ipsum dolor sit amet consectetur adipisicing elit. Earum aut
            molestiae doloribus labore possimus dolorem ipsam aliquid tempora
            eligendi velit. Sed voluptate voluptatibus quis tenetur aspernatur
            optio ullam blanditiis adipisci.
          </p>
        </div>
      </div> */}
    </section>
  );
};

export default Home;
